import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["Rajdhani", "sans-serif"],
      },
      fontSize: {
        "fluid-sm":  "clamp(0.875rem, 1.5vw, 1rem)",
        "fluid-base": "clamp(1rem, 2vw, 1.125rem)",
        "fluid-lg":  "clamp(1.125rem, 2.5vw, 1.375rem)",
        "fluid-xl":  "clamp(1.25rem, 3vw, 1.75rem)",
        "fluid-2xl": "clamp(1.5rem, 4vw, 2.25rem)",
        "fluid-3xl": "clamp(1.875rem, 5vw, 3rem)",
        "fluid-4xl": "clamp(2.25rem, 6vw, 3.75rem)",
        "fluid-5xl": "clamp(3rem, 8vw, 5rem)",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50:  "hsl(var(--primary) / 0.05)",
          100: "hsl(var(--primary) / 0.1)",
          200: "hsl(var(--primary) / 0.2)",
          300: "hsl(var(--primary) / 0.3)",
          400: "hsl(var(--primary) / 0.4)",
          500: "hsl(var(--primary) / 0.5)",
          600: "hsl(var(--primary) / 0.6)",
          700: "hsl(var(--primary) / 0.7)",
          800: "hsl(var(--primary) / 0.8)",
          900: "hsl(var(--primary) / 0.9)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Extended semantic tokens
        surface: {
          DEFAULT: "hsl(var(--surface))",
          elevated: "hsl(var(--surface-elevated))",
          overlay: "hsl(var(--surface-overlay))",
        },
        // Brand accent tokens
        cyan: {
          DEFAULT: "hsl(var(--cyan))",
          50:  "hsl(var(--cyan) / 0.05)",
          100: "hsl(var(--cyan) / 0.1)",
          200: "hsl(var(--cyan) / 0.2)",
          300: "hsl(var(--cyan) / 0.3)",
          400: "hsl(var(--cyan) / 0.4)",
          500: "hsl(var(--cyan) / 0.5)",
          600: "hsl(var(--cyan) / 0.6)",
          700: "hsl(var(--cyan) / 0.7)",
          800: "hsl(var(--cyan) / 0.8)",
          900: "hsl(var(--cyan) / 0.9)",
        },
        magenta: {
          DEFAULT: "hsl(var(--magenta))",
          50:  "hsl(var(--magenta) / 0.05)",
          100: "hsl(var(--magenta) / 0.1)",
          200: "hsl(var(--magenta) / 0.2)",
          500: "hsl(var(--magenta) / 0.5)",
        },
        lime: {
          DEFAULT: "hsl(var(--lime))",
          50:  "hsl(var(--lime) / 0.05)",
          100: "hsl(var(--lime) / 0.1)",
          200: "hsl(var(--lime) / 0.2)",
          500: "hsl(var(--lime) / 0.5)",
        },
        neon: {
          cyan:    "hsl(var(--neon-cyan))",
          magenta: "hsl(var(--neon-magenta))",
          lime:    "hsl(var(--neon-lime))",
          blue:    "hsl(var(--neon-blue))",
        },
      },
      borderRadius: {
        "4xl": "2rem",
        "3xl": "1.5rem",
        "2xl": "1rem",
        xl:   "0.75rem",
        lg:   "var(--radius)",
        md:   "calc(var(--radius) - 2px)",
        sm:   "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        "neon-cyan":    "0 0 10px hsl(var(--neon-cyan) / 0.4), 0 0 40px hsl(var(--neon-cyan) / 0.15), 0 0 80px hsl(var(--neon-cyan) / 0.05)",
        "neon-magenta": "0 0 10px hsl(var(--neon-magenta) / 0.4), 0 0 40px hsl(var(--neon-magenta) / 0.15)",
        "neon-lime":    "0 0 10px hsl(var(--neon-lime) / 0.4), 0 0 40px hsl(var(--neon-lime) / 0.15)",
        "neon-blue":    "0 0 10px hsl(var(--neon-blue) / 0.5), 0 0 40px hsl(var(--neon-blue) / 0.2)",
        "card":         "0 1px 3px hsl(var(--foreground) / 0.04), 0 4px 16px hsl(var(--foreground) / 0.06)",
        "card-hover":   "0 4px 20px hsl(var(--foreground) / 0.08), 0 8px 40px hsl(var(--foreground) / 0.06)",
        "card-glow":    "0 0 0 1px hsl(var(--cyan) / 0.2), 0 4px 20px hsl(var(--cyan) / 0.08)",
        "inner-glow":   "inset 0 1px 0 hsl(var(--foreground) / 0.06)",
        "glass":        "0 8px 32px hsl(0 0% 0% / 0.12), inset 0 1px 0 hsl(0 0% 100% / 0.08)",
      },
      backgroundImage: {
        "gradient-radial":   "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":    "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "gradient-cyber":    "linear-gradient(135deg, hsl(var(--primary)), hsl(var(--cyan)))",
        "gradient-hero":     "linear-gradient(135deg, hsl(var(--primary) / 0.9), hsl(var(--cyan) / 0.8))",
        "gradient-card":     "linear-gradient(135deg, hsl(var(--card)), hsl(var(--surface-elevated)))",
        "gradient-neon":     "linear-gradient(90deg, hsl(var(--neon-cyan)), hsl(var(--neon-magenta)))",
        "gradient-shimmer":  "linear-gradient(90deg, transparent 0%, hsl(var(--foreground) / 0.04) 50%, transparent 100%)",
        "noise":             "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.03'/%3E%3C/svg%3E\")",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to:   { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to:   { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to:   { opacity: "1" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        "fade-down": {
          from: { opacity: "0", transform: "translateY(-20px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-left": {
          from: { opacity: "0", transform: "translateX(-30px)" },
          to:   { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(30px)" },
          to:   { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.92)" },
          to:   { opacity: "1", transform: "scale(1)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%":      { transform: "translateY(-10px)" },
        },
        "float-slow": {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%":      { transform: "translateY(-16px) rotate(2deg)" },
        },
        "shimmer": {
          from: { backgroundPosition: "-200% 0" },
          to:   { backgroundPosition: "200% 0" },
        },
        "gradient-shift": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%":      { backgroundPosition: "100% 50%" },
        },
        "scanline": {
          "0%":   { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(100vh)" },
        },
        "glow-pulse": {
          "0%, 100%": { opacity: "1", boxShadow: "0 0 10px hsl(var(--neon-cyan) / 0.4)" },
          "50%":      { opacity: "0.7", boxShadow: "0 0 25px hsl(var(--neon-cyan) / 0.7), 0 0 50px hsl(var(--neon-cyan) / 0.3)" },
        },
        "border-glow": {
          "0%, 100%": { borderColor: "hsl(var(--cyan) / 0.3)" },
          "50%":      { borderColor: "hsl(var(--cyan) / 0.8)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "1" },
          "50%":      { opacity: "0.5" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to:   { transform: "rotate(360deg)" },
        },
        "ping-slow": {
          "75%, 100%": { transform: "scale(1.8)", opacity: "0" },
        },
        "counter": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        "marquee": {
          from: { transform: "translateX(0)" },
          to:   { transform: "translateX(-50%)" },
        },
        "typewriter": {
          from: { width: "0" },
          to:   { width: "100%" },
        },
        "blink": {
          "0%, 100%": { opacity: "1" },
          "50%":      { opacity: "0" },
        },
      },
      animation: {
        "accordion-down":  "accordion-down 0.2s ease-out",
        "accordion-up":    "accordion-up 0.2s ease-out",
        "fade-in":         "fade-in 0.4s ease-out",
        "fade-up":         "fade-up 0.5s ease-out",
        "fade-down":       "fade-down 0.5s ease-out",
        "slide-in-left":   "slide-in-left 0.5s ease-out",
        "slide-in-right":  "slide-in-right 0.5s ease-out",
        "scale-in":        "scale-in 0.3s ease-out",
        "float":           "float 3s ease-in-out infinite",
        "float-slow":      "float-slow 6s ease-in-out infinite",
        "shimmer":         "shimmer 2s linear infinite",
        "gradient-shift":  "gradient-shift 4s ease infinite",
        "scanline":        "scanline 8s linear infinite",
        "glow-pulse":      "glow-pulse 2s ease-in-out infinite",
        "border-glow":     "border-glow 2s ease-in-out infinite",
        "pulse-glow":      "pulse-glow 2s ease-in-out infinite",
        "spin-slow":       "spin-slow 12s linear infinite",
        "ping-slow":       "ping-slow 2.5s cubic-bezier(0,0,0.2,1) infinite",
        "marquee":         "marquee 25s linear infinite",
        "typewriter":      "typewriter 3s steps(40, end)",
        "blink":           "blink 1s step-end infinite",
      },
      transitionTimingFunction: {
        "spring":      "cubic-bezier(0.175, 0.885, 0.32, 1.275)",
        "smooth":      "cubic-bezier(0.4, 0, 0.2, 1)",
        "bounce-in":   "cubic-bezier(0.68, -0.55, 0.265, 1.55)",
      },
      transitionDuration: {
        "250": "250ms",
        "350": "350ms",
        "400": "400ms",
        "600": "600ms",
        "800": "800ms",
        "1200": "1200ms",
      },
      spacing: {
        "18": "4.5rem",
        "22": "5.5rem",
        "30": "7.5rem",
        "34": "8.5rem",
        "68": "17rem",
        "76": "19rem",
        "84": "21rem",
        "88": "22rem",
        "92": "23rem",
        "100": "25rem",
        "112": "28rem",
        "128": "32rem",
      },
      blur: {
        "4xl": "80px",
        "5xl": "120px",
      },
      backdropBlur: {
        "4xl": "80px",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
